### ISSUE TITLE
Info manuals not displaying

### ISSUE THREAD

**Issue by lboogaard** [conda-forge/gnuastro-feedstock#12]
After `conda install gnuastro` calling `info gnuastro` does not work. Is this the expected behaviour?

**Comment by sebastian-luna-valero** [comment]
Thanks @lboogaard

I will let @mohammad-akhlaghi reply this.

**Comment by mohammad-akhlaghi** [comment]
Thanks a lot for reporting this @lboogaard :+1:. 

The Info manual is installed with the Conda download and put in the `PREFIX/share/info` directory, where `PREFIX` is the running Conda installation directory. Can you find this directory in your system? It contains files like `gnuastro.info.1`, `gnuastro.info.2`, ..., `gnuastro.info.7`.

There are [multiple ways](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Other-Info-Directories.html) for the system to recognize the info files. Probably the best one (that we can later bring into Conda) is the `INFOPATH` environment variable. So as a first try, can you update this environment variable (just changing `PREFIX`):

```shell
export INFOPATH="PREFIX/share/info:$INFOPATH"
```

Then try the `info gnuastro` command, and hopefully it will work. If it does, then we need to find a way to do this step within the Condaforge build recipes for Gnuastro (that is upto Sebastian and I :wink:). 

If it doesn't work, can you try going through [this section of the Texinfo manual](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Installing-an-Info-File.html) to find the best way that does work for your system (I don't have much time these days to test personally right now, see below). Once we know the solution, we can find a way to implement it in the build recipes for Gnuastro on Condaforge.

Sorry for the late reply, I have just started my new job at CEFCA and in the last few weeks I was too busy moving from my old institute/city, and had no time to read or answer most emails unfortunately. But I am back now and will hopefully get back to normal speed shortly.

**Comment by lboogaard** [comment]
Thanks @mohammad-akhlaghi ! After running `export INFOPATH="$CONDA_PREFIX/share/info:$INFOPATH"` I can indeed use `info gnuastro` as normal.

**Comment by mohammad-akhlaghi** [comment]
Great! Thanks for the fast check @lboogaard :+1:.

@sebastian-luna-valero, you are more familiar with the Conda build receipts. What is the best way to add `$CONDA_PREFIX/share/info` to the `INFOPATH` environment variable automatically everytime that Conda is loaded (of course, after Gnuastro is installed)? 

Since a single addition of this directory to `INFOPATH` is enough for all the programs that have an Info manual, ideally, we should check, and only add it when its not present already.

**Comment by sebastian-luna-valero** [comment]
Hi,

Interesting!

On the one hand, I am not sure that we can configure and export environment variables from the conda recipe itself.

On the other hand, the following worked for me on a clean terminal:
```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p conda-install
source conda-install/etc/profile.d/conda.sh 
conda create -n gnuastro -c conda-forge gnuastro
conda activate gnuastro
info gnuastro
```
`echo $INFOPATH` returned always empty to me.

@lboogaard what did you have in `echo $INFOPATH`?

Best regards,
Sebastian

**Comment by lboogaard** [comment]
@mohammad-akhlaghi I agree, since many packages can provide info, it would make more sense for the conda setup to configure the infopath.

@sebastian-luna-valero That's interesting. So perhaps conda does already configure this (but for some reason did not on my end). In any case, the $INFOPATH` was empty.

**Comment by mohammad-akhlaghi** [comment]
About why an empty `INFOPATH` was problematic for @lboogaard, but not problematic for @sebastian-luna-valero: maybe in @lboogaard's configuration, `info` is not part of Conda, but from the host operating system. Because `INFOPATH` should only be necessary when we want to look into a non-"standard" directory. However, when `info` is actually installed in a certain location (for example `$CONDA_PREFIX/bin`), then `$CONDA_PREFIX/share/info` should be a "standard" location.

One fast way to check is to see where the `info` executable comes from? @lboogaard and @sebastian-luna-valero, can you try this command and see if `info` is actually in the operating system, or part of the conda environment?

```shell
which info
```

**Comment by sebastian-luna-valero** [comment]
In my case, it's the operating system:
```
(gnuastro) $ which info
/usr/bin/info
```

**Comment by mohammad-akhlaghi** [comment]
Thanks @sebastian-luna-valero! It just got more complicated! So your OS operating system can somehow find the info manuals installed by Conda! We need to check if the Info manual you are seeing is actually the same Info manuals of Conda then.

Do you have Gnuastro in the OS (outside of Conda)? You can test with a simple `asttable --version`. If this works and Gnuastro was built from source, the Info files should be in `/usr/local/share/info`. If they are there, you can try temporarily renaming this directory and running `info gnuastro` again to see if it works this time (that you OS Info manuals are not in a standard location).

**Comment by sebastian-luna-valero** [comment]
I only have `gnuastro` installed with conda. When I try on a different terminal:
```
$ asttable --version

Command 'asttable' not found, but can be installed with:

sudo apt install gnuastro
```
Thanks for your help!

**Comment by mohammad-akhlaghi** [comment]
Thanks a lot! Then, Conda is modifying the Info directory information on your system in another way (not through `INFOPATH`). Since we haven't made any changes in Gnuastro's build receipt, it should be a pretty low-level thing in Conda. Can you ask the people more familiar with the core of Conda about this?

@lboogaard, can you try the commands of @sebastian-luna-valero for a clean/new conda environment in a [previous comment](https://github.com/conda-forge/gnuastro-feedstock/issues/12#issuecomment-919987498)? Maybe there is a problem/conflict in the current conda environment you are testing in?

**Comment by lboogaard** [comment]
Hi - I just went back to this (sorry for the late reply I somehow missed the previous message!):

Calling `info gnuastro` now works after installing `gnuastro` in a clean environment, without setting `INFOPATH`. Not sure what caused the original hiccup in the end (was tested in a clean environment after a fresh `miniconda` installation), but the issue no longer seems to appear, so I think this can be closed.
